---
- name: NGINX | Install and cofigure NGINX
  hosts: nginx
  become: true
  vars:
    nginx_listen_port: 8080

  tasks:
    - name: update
      apt:
        update_cache=yes
      tags:
        - update apt

    - name: NGINX | Install NGINX
      apt:
        name: nginx
        state: latest
      notify:
        - restart nginx
        - update_cache
      tags: nginx-package

    - name: NGINX | Create NGINX config file from template
      template:
        src: templates/nginx.conf.j2
        dest: /tmp/nginx.conf
      notify:
          - reload nginx
      tags:
        - nginx-configuration

    - name: Allow all access to tcp port 8080
      ufw:
        rule: allow
        port: '8080'
        proto: tcp

  handlers:
    - name: restart nginx
      systemd:
       name: nginx
       state: restarted
       enable: yes

    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded 

   

